### ISSUE TITLE
Front of card being emptied

### ISSUE THREAD

**Issue by sluggi** [BlueGreenMagick/edit-field-during-review-fork#2]
I saw the 9/12/19 review talking about cards being deleted, and I wanted to let you know that I also experienced the same issue. This has never happened to me before installing this add-on.

I had 2 cards have their cloze formatting removed. For instance: "I like {{c1::apples}}" became simply "I like apples". As far as I am aware, only the "Text" field is being changed.

The add-ons I have enabled are: 
- Clickable Tags v10
- Create Filtered Deck from the Browser
- Edit Field During Review Cloze
- Hierachical Tags Addon 20 21
- Hint Hotkeys
- Pop-up Dictionary beta
- ReMemorize Rescheduler with sibling and logging v114
- Special Fields

I am using Anki Version 2.1.15.

My cards are of all the same type, Cloze-AnKingMaster, which has multiple fields on it (e.g., "text", "extra", "lecture notes", hints, etc.).

**Comment by NicolasCuri** [comment]
Yeah, I was the one who wrote that review. Here is a .gif of me reproducing the bug with ALL add-ons disabled, except for Edit Cloze During Review: [https://imgur.com/a/w8c32mc](https://imgur.com/a/w8c32mc)

I'm using Anki 2.1.15 on macOS High Sierra 10.13.6

I've been using this add-on since its launch, and this bug only started happening with the latest update.

**Comment by glutanimate** [comment]
Based on some [troubleshooting work on Reddit](https://www.reddit.com/r/Anki/comments/d4enlq/anyone_else_experiencing_this_bug_with_edit_field/f0aycpi/), it seems like this earlier commit might be the issue: https://github.com/BlueGreenMagick/edit-field-during-review-fork/commit/d52c08d5e0c0819b647afedaaf93ea2f9bd10fed

**Comment by BlueGreenMagick** [comment]
I found what might be wrong, and hopefully commit 5f71dff should fix it. Could anyone with the issue try replacing __init__.py in add-on directory with this file: [link](https://raw.githubusercontent.com/BlueGreenMagick/edit-field-during-review-fork/master/__init__.py) and see if it works?

**Comment by BlueGreenMagick** [comment]
NicholasCuri replied in reddit that 5f71dff fixed the issue. I uploaded the add-on on Ankiweb, so updating the addon should fix the issue.

**Comment by glutanimate** [comment]
@BlueGreenMagick Nice job!
