### ISSUE TITLE
MathJax support?

### ISSUE THREAD

**Issue by NicolasCuri** [BlueGreenMagick/edit-field-during-review-fork#3]
Hey, is it possible that this add-on supports MathJax as well? If I have a chemical/math equation in my editable field, they turn into "pictures", just like the [...] bug I previously reported. WIth MathJax available in fields I'd have a card like:

Q: What is the chemical equation for hydrogen combustion?
A: ![image](https://user-images.githubusercontent.com/39147974/65397714-5b5ec280-dd80-11e9-9e65-89c578a70557.png)
  and after clicking the field to edit it, I'd see \[\ce{H2 + 1/2O2 -> H2O}\] (as it is the editor's appearance).

Thank you!

**Comment by BlueGreenMagick** [comment]
I hadn't known it did not work for Mathjax. Will definitely work on it!

**Comment by BlueGreenMagick** [comment]
commit https://github.com/BlueGreenMagick/edit-field-during-review-fork/commit/73d9f17698fc52fd313007888a8f3f14a7ab36ba should have fixed the issue. I will test the code for a while before uploading it to Ankiweb, but meanwhile you can copy paste the code if you need to.

**Comment by NicolasCuri** [comment]
Thank you so much! It is working perfectly!
